language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "Starting build"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  
  - docker tag udagram-api-feed joeljames270/udagram-api-feed:v0
  - docker tag udagram-frontend joeljames270/udagram-frontend:v0
  - docker tag udagram-api-user joeljames270/udagram-api-user:v0
  - docker tag reverseproxy joeljames270/reverseproxy:v0

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joeljames270/udagram-api-feed:v0
  - docker push joeljames270/udagram-frontend:v0
  - docker push joeljames270/udagram-api-user:v0
  - docker push joeljames270/reverseproxy:v0